### ISSUE TITLE
 Provided id of the wrong type for class UserType. Expected: class Short, got class Integer

### ISSUE THREAD

**Issue by ganithDev** [ganithDev/myJobsSQE#6]
org.hibernate.TypeMismatchException: Provided id of the wrong type for class com.cv_gn.model.UserType. Expected: class java.lang.Short, got class java.lang.Integer
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:133)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1066)
	at org.hibernate.internal.SessionImpl.access$2000(SessionImpl.java:176)
	at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.getReference(SessionImpl.java:2517)
	at org.hibernate.internal.SessionImpl.load(SessionImpl.java:941)
	at com.cv_gn.dao.PersonDAOImpl.addPerson(PersonDAOImpl.java:133)
	at com.cv_gn.controller.UserRegistrationController.processRequest(UserRegistrationController.java:150)
	at com.cv_gn.controller.UserRegistrationController.doPost(UserRegistrationController.java:194)

**Comment by NaduniPulsarani** [comment]
Cast the Integer value to Short using Short.parseShort method
